### ISSUE TITLE
Error for NSS and CSS

### ISSUE THREAD

**Issue by renyuneyun** [Otto-AA/solid-oidc-py#1]
I'm trying out this library, in the hope to create a PR for [solid-file-python](https://github.com/twonote/solid-file-python).
My attempt is by copy-pasting the example code until the line for `login_url`. Then, I open the link on my browser.

It seems to work with ESS -- the Inrupt server in the example. But it errors out for both NSS and CSS.

> I'm using private browsing mode, so it won't be related to my browser cookies.

### NSS
I tested https://solidweb.org and https://solidcommunity.net, which both run NSS.
`Internal Server Error` will be seen if visiting the link.

### CSS
For my custom CSS server, it gives the following error at the line for `solid_oidc_client.register_client()`:
```
Got error response: {"name": "InvalidClientMetadata", "message": "invalid_client_metadata", "error": "invalid_client_metadata", "error_description": "request_uris must only contain web uris", "statusCode": <REDACTED>, "errorCode": "<REDACTED>"}
```

Then stack trace:

```
RegistrationError                         Traceback (most recent call last)
Cell In[12], line 1
----> 1 solid_oidc_client.register_client('https://MY-OWN-CSS-SERVER/', [OAUTH_CALLBACK_URI])

File ~/venvs/solid-fuse-iNTciV4e-py3.11/lib/python3.11/site-packages/solid_oidc_client/solid_oidc_client.py:31, in SolidOidcClient.register_client(self, issuer, redirect_uris)
     29 """Register this client for a specific identity provider"""
     30 self.provider_info = self.client.provider_config(issuer)
---> 31 registration_response = self.client.register(
     32         self.provider_info['registration_endpoint'],
     33         redirect_uris=redirect_uris)
     34 self.client_id = registration_response['client_id']
     35 self.client_secret = registration_response['client_secret']

File ~/venvs/solid-fuse-iNTciV4e-py3.11/lib/python3.11/site-packages/oic/oic/__init__.py:1416, in Client.register(self, url, registration_token, **kwargs)
   1412         headers["Authorization"] = "Bearer " + registration_token
   1414 rsp = self.http_request(url, "POST", data=req.to_json(), headers=headers)
-> 1416 return self.handle_registration_info(rsp)

File ~/venvs/solid-fuse-iNTciV4e-py3.11/lib/python3.11/site-packages/oic/oic/__init__.py:1306, in Client.handle_registration_info(self, response)
   1304     if self.events:
   1305         self.events.store("protocol response", resp)
-> 1306     raise RegistrationError(resp.to_dict())
   1307 else:  # Something else
   1308     logger.error(unk_msg.format(sanitize(response.text)))

RegistrationError: {'name': 'InvalidClientMetadata', 'message': 'invalid_client_metadata', 'error': 'invalid_client_metadata', 'error_description': 'request_uris must only contain web uris', 'statusCode': 400, 'errorCode': 'H400'}
```

**Comment by Otto-AA** [comment]
Hi, thanks for letting me know.

For NSS, the example app still works (https://github.com/Otto-AA/solid-flask). I was able to login with `python solid_flask_main.py --issuer https://solidcommunity.net/` and read a private file. Could you check if the example app works for you? If yes, try to compare the parameters from this app to your app.

I'll take a look at the CSS error, at least on the first try I've got the same error as you.

**Comment by Otto-AA** [comment]
The problem with CSS arises because:
- it requires request_uri registration and solid-oidc-py fails with this (I'll look more into what this is). NSS and ESS don't require this currently.
- it requires a minimum length of 43 chars for the code_verifier, the uuid used only has 36

As a hacky workaround, you could change solid_oidc_client.py to:

1. Include a base_uri (this makes the request_uri stuff not fail, but no idea where this base_url would be used)

```python
class SolidOidcClient:
    """Client to handle Solid-OIDC authentication. Create one per identity provider"""
    def __init__(self, storage: KeyValueStore) -> None:
        self.client = OicClient(client_authn_method=CLIENT_AUTHN_METHOD)
        # TODO: why is this necessary?
        self.client.base_url = "https://thispageisirrelevant.abc/"
        self.storage = storage
```

2. Increase the length of the code_verifier

```python
def create_verifier_challenge():
    # TODO: check why CSS requires 43+ chars of code_verifier.
    code_verifier = str(uuid4()) + str(uuid4())
```

With these changes, the flask example app also works with `python solid_flask_main.py --issuer https://solidweb.me/`.

**Comment by Otto-AA** [comment]
I've included the changes in the solid-oidc-client 0.0.4 release. I've also updated the version in the example app, so if you try it there (with the current dependencies) CSS should also work. Can you confirm that? If everything works, feel free to close the issue :)

As far as I've seen, the `request_uri` is not used by this project, so we can leave it as any base_url. And the code_verifier must indeed be at least 43 chars according to the specification.

**Comment by renyuneyun** [comment]
Hi. Thanks for the updates.
The example app also works on my end. After looking into details, it seems the different behaviour is caused by different redirect urls supplied to `solid_oidc_client.create_login_uri()`:
- In the example app, this url contains the protocol and domain, and the path, e.g. `http://localhost/oauth/callback`
- In the README (of this repo), this url only contains the path, e.g. `/oauth/callback`.

After changing this part, the generated URL seems to work.

This had better be documented.

In fact, it is confusing why there are two places for callback url, one with `solid_oidc_client.register_client()`, and one with `solid_oidc_client.create_login_uri()`. Probably it's also worth documenting their relationship as well.

**Comment by Otto-AA** [comment]
Thanks for the feedback. I've fixed the example callback uri and updated the comments, is it more clear now?

**Comment by renyuneyun** [comment]
Thanks for the update. The document is much clearer now.
I also had a test of CSS for v0.0.4, and it's working fine. I'll close this issue.
